# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d6989f00dd6d04963d4ba900ad1cd9c0b6296a7ae642c78266ed397b7e7f841c79c49ae893db3615c93e8841ba0997cb7104a0c7da088b87e48ba79c7ccb0db

test:
  secret_key_base: f0dd564c897102f155d45f322073260919d5c494ad1e90363ccba657b76f9cf46afc9cab0d3ceffed58af83651c019b4261595daf384290955c0bcb94a4b48e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
